quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: mysecretpassword
    jdbc:
      url: jdbc:postgresql://localhost:5432/platypus

  flyway:
    migrate-at-start: true
    locations: db/0_tables,db/1_data